---
- name: Creacion de usuario de aplicacion
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    priv: "app.*:ALL"
    state: present
  with_items: "{{ mysql_users }}"
 